repos:
  # Backend hooks
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^backend/
        exclude: ^backend/(data/|.venv/|EDAM_obsolete.json)

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        files: ^backend/
        exclude: ^backend/(data/|.venv/|EDAM_obsolete.json)
        args: ['--max-line-length=88', '--extend-ignore=E203,W503']

  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|css|json|html)$
        exclude: ^frontend/(node_modules|bower_components|dist|lib|static|resources|css|(js/lib))/
        additional_dependencies:
          - prettier@2.8.8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.13.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.js$
        exclude: ^frontend/(node_modules|bower_components|dist|lib|static|resources|css|(js/lib))/
        additional_dependencies:
          - eslint@8.57.0

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(frontend/(node_modules|bower_components|dist|lib|static|resources))
      - id: end-of-file-fixer
        exclude: ^(frontend/(node_modules|bower_components|dist|lib|static|resources))
      - id: check-yaml
        exclude: ^(frontend/(node_modules|bower_components|dist|lib|static|resources))
      - id: check-json
        exclude: ^(frontend/(node_modules|bower_components|dist|lib|static|resources))
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: mixed-line-ending
